### ISSUE TITLE
Not Able to rectify this error. Please Help

### ISSUE THREAD

**Issue by HadesA1** [BakingBrains/Pose_estimation#2]
line 52, in main
    print(lmList[14])
IndexError: list index out of range

Process finished with exit code 1

**Comment by BakingBrains** [comment]
@HadesA1 Just try using ```print(lmList)```

**Comment by HadesA1** [comment]
i tried sir
it puts out this error 
line 56, in main
    cv2.circle(lmList[14][1], lmList[14][2], 5, (0, 0, 0), cv2.FILLED)
IndexError: list index out of range

and if i comment that line it does not print all the 32 points. it only prints the 0th point
It prints it out like this :
[[0, 1173, 218]]
[[0, 1167, 217]]
[[0, 1162, 216]]
[[0, 1166, 206]]
[[0, 1160, 212]]
[[0, 1154, 216]]
[[0, 1156, 217]]
[[0, 1154, 227]]
[[0, 1146, 243]]
[[0, 1134, 265]]
[[0, 1122, 278]]
[[0, 1118, 292]]
[[0, 1113, 310]]
[[0, 1109, 322]]
[[0, 1111, 324]]
[[0, 1104, 316]]
[[0, 1097, 318]]
[[0, 1087, 315]]

**Comment by BakingBrains** [comment]
@HadesA1 can you plz tell which code are you executing?
Also you can debug the code and get more insights as well.

**Comment by HadesA1** [comment]
I'm executing the poseModule
I'm new to this sir 



import cv2
import mediapipe as mp
import time


class poseDetector:

    def __init__(self, mode=False, modelComplex=1, upBody=False, smooth=True, detectionCon=0.5, trackCon=0.5,):

        self.modelComplex = modelComplex
        self.mode = mode
        self.upBody = upBody
        self.smooth = smooth
        self.detectionCon = detectionCon
        self.trackCon = trackCon

        self.mpDraw = mp.solutions.drawing_utils
        self.mpPose = mp.solutions.pose
        self.pose = self.mpPose.Pose(self.mode, self.modelComplex, self.upBody, self.smooth, self.detectionCon, self.trackCon)

    def findPose(self, img, draw=True):
        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        self.results = self.pose.process(imgRGB)
        # print(results.pose_landmarks)
        if self.results.pose_landmarks:
            if draw:
                self.mpDraw.draw_landmarks(img, self.results.pose_landmarks, self.mpPose.POSE_CONNECTIONS)

        return img

    def findPosition(self, img, draw=True):
        lmList = []
        if self.results.pose_landmarks:
            for id, lm in enumerate(self.results.pose_landmarks.landmark):
                h, w, c = img.shape
                img = cv2.resize(img, (1080, 600))

                #print(id, lm)
                cx, cy = int(lm.x * w), int(lm.y * h)
                lmList.append([id, cx, cy])
                if draw:
                    cv2.circle(img, (cx, cy), 5, (0, 0, 255), cv2.FILLED)
                return lmList


def main():
    cap = cv2.VideoCapture('Images/7.mp4')
    pTime = 0
    detector = poseDetector()
    while True:
        success, img = cap.read()
        img = detector.findPose(img)
        lmList = detector.findPosition(img)
        if len(lmList) != 0:
            print(lmList)
            #cv2.circle(lmList[14][1], lmList[14][2], 5, (0, 0, 0), cv2.FILLED)
        cTime = time.time()
        fps = 1 / (cTime - pTime)
        pTime = cTime

        cv2.putText(img, str(int(fps)), (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0), 3)
        cv2.imshow("Image", img)
        cv2.waitKey(1)


if __name__ == "__main__":
    main()
And another

**Comment by BakingBrains** [comment]
@HadesA1 Is the issue resolved?
